png(file = "plot3.png", width = 480, height = 480)
a <- read.delim("household_power_consumption.txt", sep = ";", na.strings = "?")
library(lubridate)
a[ ,"Date"] <- dmy(a[ ,"Date"])
c <- subset(a, a[ , "Date"] == "2007-02-01" | a[ , "Date"] == "2007-02-02")
c$combine <- paste(c$Date, c$Time)
c$combine <- ymd_hms(c$combine)
with(c, {
  plot(combine,Sub_metering_1, type = "n",xlab = " ", ylab = "Energy sub metering")
  lines(combine,Sub_metering_1, type = "l", col = "grey", lwd = 3)
  lines(combine,Sub_metering_2, type = "l", col = "red")
  lines(combine,Sub_metering_3, type = "l", col = "blue")
})
legend("topright",lty = c(1,1,1) ,lwd = 2,col = c("grey","red","blue"), legend = c("sub_metering_1", "sub_metering_2", "sub_metering_3"))
dev.off()