png(file = "plot2.png", width = 480, height = 480)
a <- read.delim("household_power_consumption.txt", sep = ";", na.strings = "?")
library(lubridate)
a[ ,"Date"] <- dmy(a[ ,"Date"])
c <- subset(a, a[ , "Date"] == "2007-02-01" | a[ , "Date"] == "2007-02-02")
c$combine <- paste(c$Date, c$Time)
c$combine <- ymd_hms(c$combine)
with(c, plot(combine,Global_active_power, type = "n",ylab = "Global Active Power (kilowatts)", xlab =" "))
with(c, lines(combine,Global_active_power, type = "l"))
dev.off()